name: Lint
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8459bc0c7e3759cdf591f513d9f141a95fef0a8f
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}/node-18/${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}/node-18/
      - run: yarn
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - run: yarn lint
